Repository Anwesha-2k23/backend, pull requests merged in 2022-10, with the labels that each got.

#37 crashes fix
  anwesha/anwesha/asgi.py
  anwesha/anwesha/settings.py
  anwesha/anwesha/urls.py
  anwesha/anwesha/wsgi.py
  anwesha/event/admin.py
  anwesha/event/apps.py
  anwesha/event/migrations/0001_initial.py
  anwesha/event/models.py
  anwesha/event/tests.py
  anwesha/event/views.py
  anwesha/manage.py
  anwesha/map/admin.py
  anwesha/map/apps.py
  anwesha/map/models.py
  anwesha/map/tests.py
  anwesha/map/views.py
  anwesha/user/admin.py
  anwesha/user/apps.py
  anwesha/user/migrations/0001_initial.py
  anwesha/user/migrations/0003_alter_user_accomadation_selected_and_more.py
  anwesha/user/migrations/0004_alter_user_user_type.py
  anwesha/user/migrations/0005_alter_user_anwesha_id.py
  anwesha/user/migrations/0006_alter_user_anwesha_id.py
  anwesha/user/models.py
  anwesha/user/tests.py
  anwesha/user/urls.py
  anwesha/user/views.py
Labels: hacktoberfest

#40 Get event by Id api added
  anwesha/event/models.py
  anwesha/event/urls.py
  anwesha/event/views.py
  anwesha/user/migrations/0007_merge_0002_alter_user_age_0006_alter_user_anwesha_id.py
  anwesha/user/migrations/0008_alter_user_accomadation_selected_alter_user_age_and_more.py
  anwesha/user/models.py
Labels: hacktoberfest-accepted

#43 Filter Events API added
  anwesha/event/migrations/0002_events_tags.py
  anwesha/event/migrations/0003_alter_events_tags.py
  anwesha/event/migrations/0004_alter_events_tags.py
  anwesha/event/migrations/0005_alter_events_tags.py
  anwesha/event/migrations/0006_alter_events_tags.py
  anwesha/event/models.py
  anwesha/event/urls.py
  anwesha/event/views.py
Labels: hacktoberfest, hacktoberfest-accepted

#44 user model updated and edit profile api added
  anwesha/anwesha/settings.py
  anwesha/user/models.py
  anwesha/user/urls.py
  anwesha/user/views.py
  requirements.txt
Labels: hacktoberfest-accepted

#53 bug fixes
  anwesha/static/qrcode/ANW7758958909.png
  anwesha/user/views.py
Labels: hacktoberfest, hacktoberfest-accepted

#52 Gallery model added
  anwesha/event/admin.py
  anwesha/event/migrations/0007_gallery.py
  anwesha/event/migrations/0008_remove_gallery_element_gallery_file_and_more.py
  anwesha/event/migrations/0009_gallery_timestamp.py
  anwesha/event/models.py
  anwesha/user/urls.py
  anwesha/user/views.py
Labels: hacktoberfest, hacktoberfest-accepted

#55 integrated aws credentials
  .gitignore
  anwesha/anwesha/settings.py
  anwesha/anwesha/storage_backend.py
  anwesha/participant/urls.py
  anwesha/user/migrations/0013_merge_20221029_0943.py
  anwesha/user/migrations/0014_alter_user_profile_photo_alter_user_qr_code.py
  anwesha/user/models.py
Labels: hacktoberfest, hacktoberfest-accepted

#56 Integrated gmail sending services
  .gitignore
  README.md
  anwesha/user/views.py
  requirements.txt
Labels: hacktoberfest-accepted

#58 qr code issue solved
  anwesha/anwesha/settings.py
  anwesha/static/qrcode/ANW7758958909.png
  anwesha/user/views.py
  anwesha/utility.py
Labels: hacktoberfest, hacktoberfest-accepted

#59 updated requirements.txt
  requirements.txt
Labels: hacktoberfest, hacktoberfest-accepted

#60 updated requirement.txt
  requirements.txt
Labels: hacktoberfest, hacktoberfest-accepted
